// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuZHurmkQeDbrYYb6e0vcDBT43iPmATmg',
    appId: '1:181999022182:web:0fec0b95f1a2628a847da7',
    messagingSenderId: '181999022182',
    projectId: 'flutter-test-e37ad',
    authDomain: 'flutter-test-e37ad.firebaseapp.com',
    storageBucket: 'flutter-test-e37ad.firebasestorage.app',
    measurementId: 'G-PR0YSGLP95',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUT_n3y3Wko3q2eDx6PxCS5thSiTEu3-8',
    appId: '1:181999022182:android:4c048366e2eb5b33847da7',
    messagingSenderId: '181999022182',
    projectId: 'flutter-test-e37ad',
    storageBucket: 'flutter-test-e37ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDespF6fNVHy2q-eYlAy7aC1RKzWNe7ae0',
    appId: '1:181999022182:ios:e15659f053dca8da847da7',
    messagingSenderId: '181999022182',
    projectId: 'flutter-test-e37ad',
    storageBucket: 'flutter-test-e37ad.firebasestorage.app',
    iosClientId: '181999022182-rkf6q1oq3lvod53423dbkpjtgitkc8ev.apps.googleusercontent.com',
    iosBundleId: 'com.example.fluttertest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDespF6fNVHy2q-eYlAy7aC1RKzWNe7ae0',
    appId: '1:181999022182:ios:e15659f053dca8da847da7',
    messagingSenderId: '181999022182',
    projectId: 'flutter-test-e37ad',
    storageBucket: 'flutter-test-e37ad.firebasestorage.app',
    iosClientId: '181999022182-rkf6q1oq3lvod53423dbkpjtgitkc8ev.apps.googleusercontent.com',
    iosBundleId: 'com.example.fluttertest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuZHurmkQeDbrYYb6e0vcDBT43iPmATmg',
    appId: '1:181999022182:web:16c8ab40666b744f847da7',
    messagingSenderId: '181999022182',
    projectId: 'flutter-test-e37ad',
    authDomain: 'flutter-test-e37ad.firebaseapp.com',
    storageBucket: 'flutter-test-e37ad.firebasestorage.app',
    measurementId: 'G-GS4WQPHG1G',
  );

}